import Form from '@/pages/form';
import Head from 'next/head'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Newsletter sign-up form</title>
        <link rel="icon" href="/favicon-32x32.png" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container  mx-auto flex justify-center items-center my-0 sm:my-36 ">
        <Form />
      </div>
    </div>
  );
}
